// <auto-generated />
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DifficultyLevel = "Intermediate",
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 2,
                            DifficultyLevel = "Intermediate",
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 3,
                            DifficultyLevel = "Advanced",
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 4,
                            DifficultyLevel = "Beginner",
                            Name = "Bicep Curl"
                        },
                        new
                        {
                            Id = 5,
                            DifficultyLevel = "Beginner",
                            Name = "Tricep Pushdown"
                        },
                        new
                        {
                            Id = 6,
                            DifficultyLevel = "Beginner",
                            Name = "Crunches"
                        },
                        new
                        {
                            Id = 7,
                            DifficultyLevel = "Intermediate",
                            Name = "Russian Twist"
                        },
                        new
                        {
                            Id = 8,
                            DifficultyLevel = "Intermediate",
                            Name = "Overhead Shoulder Press"
                        },
                        new
                        {
                            Id = 9,
                            DifficultyLevel = "Intermediate",
                            Name = "Rear Delt Fly"
                        },
                        new
                        {
                            Id = 10,
                            DifficultyLevel = "Intermediate",
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = 11,
                            DifficultyLevel = "Advanced",
                            Name = "Pull-Up"
                        },
                        new
                        {
                            Id = 12,
                            DifficultyLevel = "Intermediate",
                            Name = "Back Extension"
                        },
                        new
                        {
                            Id = 13,
                            DifficultyLevel = "Intermediate",
                            Name = "Glute Bridge"
                        },
                        new
                        {
                            Id = 14,
                            DifficultyLevel = "Intermediate",
                            Name = "Hamstring Curl"
                        },
                        new
                        {
                            Id = 15,
                            DifficultyLevel = "Beginner",
                            Name = "Calf Raise"
                        },
                        new
                        {
                            Id = 16,
                            DifficultyLevel = "Beginner",
                            Name = "Tibialis Raise"
                        },
                        new
                        {
                            Id = 17,
                            DifficultyLevel = "Beginner",
                            Name = "Forearm Curl"
                        });
                });

            modelBuilder.Entity("Domain.Models.ExerciseMuscleGroup", b =>
                {
                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("ExerciseId", "MuscleGroupId");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("ExerciseMuscleGroups");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            MuscleGroupId = 1,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 1,
                            MuscleGroupId = 9,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 2,
                            MuscleGroupId = 7,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 2,
                            MuscleGroupId = 15,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 3,
                            MuscleGroupId = 13,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 3,
                            MuscleGroupId = 15,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 4,
                            MuscleGroupId = 5,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 5,
                            MuscleGroupId = 14,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 6,
                            MuscleGroupId = 3,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 7,
                            MuscleGroupId = 4,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 8,
                            MuscleGroupId = 9,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 9,
                            MuscleGroupId = 10,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 10,
                            MuscleGroupId = 11,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 11,
                            MuscleGroupId = 12,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 12,
                            MuscleGroupId = 13,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 13,
                            MuscleGroupId = 15,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 14,
                            MuscleGroupId = 16,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 15,
                            MuscleGroupId = 8,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 16,
                            MuscleGroupId = 8,
                            Id = 0
                        },
                        new
                        {
                            ExerciseId = 17,
                            MuscleGroupId = 6,
                            Id = 0
                        });
                });

            modelBuilder.Entity("Domain.Models.MuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chest"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Traps"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Abs"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Obliques"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Biceps"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Forearms"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Quads"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Lower legs"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Front and side delts"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Posterior delts"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Upper/mid back"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Lats"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Lower back"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Triceps"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Glutes"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Hamstrings"
                        });
                });

            modelBuilder.Entity("Domain.Models.ExerciseMuscleGroup", b =>
                {
                    b.HasOne("Domain.Models.Exercise", "Exercise")
                        .WithMany("ExerciseMuscleGroups")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.MuscleGroup", "MuscleGroup")
                        .WithMany("ExerciseMuscleGroups")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("Domain.Models.Exercise", b =>
                {
                    b.Navigation("ExerciseMuscleGroups");
                });

            modelBuilder.Entity("Domain.Models.MuscleGroup", b =>
                {
                    b.Navigation("ExerciseMuscleGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
